// src/routes/settings/stores/index.svelte
<script context="module" lang="ts">
  import type { Load } from "@sveltejs/kit"
  import { browser } from "$app/env"

  export const load: Load = async ({ fetch }) => {
    const result = await fetch("/api/me/stores")

    if (result.ok) {
      return {
        status: 200,
        props: {
          stores: await result.json()
        }
      }
    }

    if (result.status === 401 && browser) {
      window.location.href = "/"
    }

    return {
      status: 302,
      redirect: "/"
    }
  }
</script>

<script lang="ts">
  import type { Store } from "$lib/domain"
  import StoreCard from "../../../lib/StoreCard.svelte"
  import SEO from "$lib/SEO.svelte"

  export let stores: Store[]
</script>

<SEO title="Semua Toko" />

<div class="max-w-7xl mx-auto flex flex-col sm:flex-row items-start flex-wrap pt-8">
  {#each stores as store}
    <StoreCard href="/settings/stores/{store.slug}">
      <div class="flex items-end">
        <h1 class="block mx-6 mb-4 text-2xl font-black">{store.name}</h1>
      </div>
    </StoreCard>
  {/each}

  <StoreCard class="border-dashed border-2 border-gray-300" href="/settings/stores/new">
    <div class="flex flex-col items-center justify-center">
      <img src="/icons/plus.svg" width="32" height="32" class="mb-2" alt=""/>
      <p>Buat toko baru</p>
    </div>
  </StoreCard>
</div>

// src/pages/me/stores.tsx
import Divider from "@components/Divider"
import React from "react"
import { findAllStores } from "@lib/db"
import { getSession } from "next-auth/client"
import { InferGetServerSidePropsType, NextPage } from "next"
import Link from "@components/Link"

const Stores: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ stores }) => {
  return (
    <div className="max-w-7xl mx-auto sm:px-6 lg:px-8 pt-8 pb-32">
      <div className="px-4 sm:px-0 mt-2 md:flex md:items-center md:justify-between">
        <div className="flex-1 min-w-0">
          <h2 className="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
            Toko anda
          </h2>
        </div>
      </div>

      <Divider />

      <ul className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {stores.map((store) => (
          <li
            key={store.id}
            className="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200"
          >
            <div className="w-full flex items-center justify-between p-6 space-x-6">
              <div className="flex-1 truncate">
                <div className="flex items-center space-x-3">
                  <h3 className="text-gray-900 text-sm font-medium truncate">{store.name}</h3>
                </div>
                <p className="mt-1 text-gray-500 text-sm truncate">{store.description}</p>
              </div>
              <img
                className="w-10 h-10 rounded-full flex-shrink-0"
                src="/icons/chevron-right.svg"
                alt=""
              />
            </div>
          </li>
        ))}
        <Link href="/me/stores/new">
          <li className="col-span-1 rounded-xl divide-y divide-gray-200 p-8 flex items-center border-2 border-dashed border-gray-400 hover:border-purple-600 mx-4 sm:mx-0">
            <p className="text-lg text-black">Buat toko baru</p>
            <img
              className="w-8 h-8 rounded-full flex-shrink-0 ml-auto opacity-80"
              src="/icons/plus.svg"
              alt=""
            />
          </li>
        </Link>
      </ul>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)
  if (session === null) {
    return {
      redirect: {
        destination: "/auth/signin",
        permanent: false
      }
    }
  }
  const stores = await findAllStores(session.user.email)

  // Pass data to the page via props
  return { props: { stores } }
}

export default Stores
