// src/pages/me/stores/index.tsx
import Divider from "@components/divider"
import React from "react"
import { findUserStores } from "@lib/db"
import { getSession } from "next-auth/client"
import { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next"
import Link from "@components/link"
import { Store } from "@prisma/client"
import SEO from "@components/seo"

const Stores: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ stores }) => {
  return (
    <div className="sm:px-6 lg:px-8 pt-8 pb-32 mx-auto max-w-7xl">
      <SEO title="Semua toko anda" />

      <div className="md:flex md:justify-between md:items-center px-4 sm:px-0 mt-2">
        <div className="flex-1 min-w-0">
          <h2 className="text-2xl sm:text-3xl font-bold leading-7 text-gray-900 sm:truncate">
            Toko anda
          </h2>
        </div>
      </div>

      <Divider />

      <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {stores.map((store) => (
          <Link key={store.id} href={`/me/stores/${store.slug}`}>
            <li className="flex col-span-1 items-center p-6 mx-4 sm:mx-0 min-h-[92px] bg-white hover:bg-primary-100 rounded-lg divide-y divide-gray-200 shadow transition-colors">
              <div className="flex-1 truncate">
                <div className="flex items-center space-x-3">
                  <h3 className="text-sm text-gray-900 truncate">{store.name}</h3>
                </div>
                <p className="mt-1 text-sm text-gray-500 truncate">{store.description}</p>
              </div>
              <img className="w-6 h-6 opacity-70" src="/icons/chevron-right.svg" alt="" />
            </li>
          </Link>
        ))}

        <Link href="/me/stores/new">
          <li className="flex col-span-1 items-center p-8 mx-4 sm:mx-0 rounded-xl border-2 border-gray-300 hover:border-primary-400 border-dashed divide-y divide-gray-200">
            <p className="text-lg text-black">Buat toko baru</p>
            <img
              className="flex-shrink-0 ml-auto w-6 h-6 rounded-full opacity-40"
              src="/icons/plus.svg"
              alt=""
            />
          </li>
        </Link>
      </ul>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<{ stores: Store[] }> = async (context) => {
  const session = await getSession(context)
  if (!session?.user?.email) {
    return {
      redirect: {
        destination: "/auth/signin",
        permanent: false
      }
    }
  }
  const stores = await findUserStores(session.user.email)

  // Pass data to the page via props
  return { props: { stores } }
}

export default Stores

// src/routes/settings/stores/index.svelte
<script context="module" lang="ts">
  import type { Load } from "@sveltejs/kit"
  import { browser } from "$app/env"

  export const load: Load = async ({ fetch }) => {
    const result = await fetch("/api/me/stores")

    if (result.ok) {
      return {
        status: 200,
        props: {
          stores: await result.json()
        }
      }
    }

    if (result.status === 401 && browser) {
      window.location.href = "/"
    }

    return {
      status: 302,
      redirect: "/"
    }
  }
</script>

<script lang="ts">
  import type { Store } from "$lib/domain"
  import StoreCard from "../../../lib/StoreCard.svelte"
  import SEO from "$lib/SEO.svelte"

  export let stores: Store[]
</script>

<SEO title="Semua Toko" />

<div class="max-w-7xl mx-auto flex flex-col sm:flex-row items-start flex-wrap pt-8">
  {#each stores as store}
    <StoreCard href="/settings/stores/{store.slug}">
      <div class="flex items-end">
        <h1 class="block mx-6 mb-4 text-2xl font-black">{store.name}</h1>
      </div>
    </StoreCard>
  {/each}

  <StoreCard class="border-dashed border-2 border-gray-300" href="/settings/stores/new">
    <div class="flex flex-col items-center justify-center">
      <img src="/icons/plus.svg" width="32" height="32" class="mb-2" alt=""/>
      <p>Buat toko baru</p>
    </div>
  </StoreCard>
</div>
